import { defineField, defineType } from "sanity";

export const concernSchema = defineType({
  name: "concern",
  title: "Concern",
  type: "document",
  groups: [
    { name: "main", title: "Main", default: true },
    { name: "detail", title: "Detail page" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "name", title: "Concern name", type: "string", group: "main", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "URL slug",
      type: "slug",
      group: "main",
      options: { source: "name", maxLength: 96 },
      validation: (r) => r.required(),
      description: "The /concerns/<slug> URL.",
    }),
    defineField({
      name: "icon",
      title: "Card icon glyph",
      type: "string",
      group: "main",
      initialValue: "◍",
      description: "A single unicode glyph (◍ ◐ ✺ ❋ ⟡ ✦ ◊ ✶ ◉ ◬ ○ ≋).",
    }),
    defineField({
      name: "cardTagline",
      title: "Card tagline",
      type: "string",
      group: "main",
      description: "Short line shown under the name on concern cards.",
    }),
    defineField({
      name: "cardImage",
      title: "Card image",
      type: "image",
      options: { hotspot: true },
      group: "main",
      description: "Optional — shown on the concern card. When set, it replaces the icon glyph.",
    }),
    defineField({
      name: "image",
      title: "Detail page image",
      type: "image",
      options: { hotspot: true },
      group: "detail",
      description: "Optional — replaces the gradient placeholder on the concern detail page.",
    }),
    defineField({
      name: "imageVariant",
      title: "Placeholder gradient",
      type: "string",
      group: "detail",
      options: { list: ["v1", "v2", "v3", "v4", "v5", "v6"].map((v) => ({ title: v, value: v })) },
      initialValue: "v1",
    }),
    defineField({ name: "headline", title: "Headline", type: "text", rows: 2, group: "detail", validation: (r) => r.required() }),
    defineField({ name: "summary", title: "Summary", type: "text", rows: 4, group: "detail", validation: (r) => r.required() }),
    defineField({ name: "symptoms", title: "Symptoms / signs", type: "array", of: [{ type: "string" }], group: "detail" }),
    defineField({ name: "causes", title: "Common causes", type: "array", of: [{ type: "string" }], group: "detail" }),
    defineField({
      name: "approach",
      title: "Our approach (paragraphs)",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      group: "detail",
    }),
    defineField({
      name: "treatments",
      title: "Recommended treatments",
      type: "array",
      of: [{ type: "reference", to: [{ type: "treatment" }] }],
      group: "detail",
      validation: (r) => r.unique(),
    }),
    defineField({ name: "faqs", title: "FAQs", type: "array", of: [{ type: "faqItem" }], group: "detail" }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
    defineField({
      name: "order",
      title: "Sort order on listing",
      type: "number",
      initialValue: 0,
      group: "main",
    }),
  ],
  orderings: [
    { name: "order", title: "Manual order", by: [{ field: "order", direction: "asc" }] },
    { name: "name", title: "Name", by: [{ field: "name", direction: "asc" }] },
  ],
  preview: { select: { title: "name", subtitle: "cardTagline", media: "image" } },
});
